
import numpy as np
import os


class IOManager:

    def __init__(self, output_dir="."):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def write_simulation_header(self, filename, params):
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("# ==========================================================\n")
            f.write("# Topological Insulator Surface State Transport Simulation\n")
            f.write("# ==========================================================\n")
            f.write(f"# Generated by sci-project-synthesis-python\n")
            f.write("#\n")
            for key, value in params.items():
                if isinstance(value, float):
                    f.write(f"{key:30s} = {value:18.10e}\n")
                elif isinstance(value, int):
                    f.write(f"{key:30s} = {value:18d}\n")
                else:
                    f.write(f"{key:30s} = {str(value):18s}\n")
            f.write("# ==========================================================\n")

    def write_matrix(self, filename, matrix, title="Matrix", fmt="%.10e"):
        filepath = os.path.join(self.output_dir, filename)
        np.savetxt(filepath, matrix, fmt=fmt, header=title, comments='# ')

    def write_vector(self, filename, vector, title="Vector", fmt="%.10e"):
        filepath = os.path.join(self.output_dir, filename)
        np.savetxt(filepath, vector, fmt=fmt, header=title, comments='# ')

    def write_zone_data(self, filename, title, variables, data_dict):
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f'TITLE = "{title}"\n')
            f.write(f'VARIABLES = "{""",""".join(variables)}"\n')
            f.write(f'ZONE T="{title}"\n')

            n_points = len(data_dict[variables[0]])
            f.write(f'I={n_points}, F=POINT\n')

            for i in range(n_points):
                row = [data_dict[var][i] for var in variables]
                f.write(' '.join([f'{v:18.10e}' for v in row]) + '\n')

    def parse_variable_line(self, line):
        line = line.strip()
        if line.upper().startswith('VARIABLES'):

            vars_list = []
            in_quote = False
            current = ''
            for c in line:
                if c == '"':
                    if in_quote and current:
                        vars_list.append(current.strip())
                        current = ''
                    in_quote = not in_quote
                elif in_quote:
                    current += c
            return vars_list
        return []

    def read_zone_data(self, filename):
        filepath = os.path.join(self.output_dir, filename)
        if not os.path.exists(filepath):
            return {}

        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        variables = None
        data_start = 0
        for i, line in enumerate(lines):
            if line.upper().startswith('VARIABLES'):
                variables = self.parse_variable_line(line)
            if 'F=POINT' in line.upper() or 'F=BLOCK' in line.upper():
                data_start = i + 1
                break

        if variables is None:
            return {}

        data = {var: [] for var in variables}
        for line in lines[data_start:]:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) >= len(variables):
                for j, var in enumerate(variables):
                    try:
                        data[var].append(float(parts[j]))
                    except ValueError:
                        data[var].append(parts[j])

        return {k: np.array(v) for k, v in data.items()}

    def write_transport_results(self, filename, results):
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("# ==========================================================\n")
            f.write("# Transport Coefficients Results\n")
            f.write("# ==========================================================\n")
            for key, value in results.items():
                if isinstance(value, (list, np.ndarray)):
                    f.write(f"\n{key}:\n")
                    for v in value:
                        f.write(f"  {v:18.10e}\n")
                elif isinstance(value, float):
                    f.write(f"{key:40s} = {value:18.10e}\n")
                else:
                    f.write(f"{key:40s} = {str(value)}\n")
            f.write("# ==========================================================\n")

    def print_matrix_transpose(self, matrix, title="", max_rows=10, max_cols=10):
        print(f"\n{title}")
        m, n = matrix.shape
        rows_to_print = min(m, max_rows)
        cols_to_print = min(n, max_cols)

        for i in range(rows_to_print):
            row_str = " ".join([f"{matrix[i, j]:12.6e}" for j in range(cols_to_print)])
            print(f"  Row {i:3d}: {row_str}")

        if m > max_rows:
            print(f"  ... ({m - max_rows} more rows)")
        if n > max_cols:
            print(f"  ... ({n - max_cols} more columns)")
