"""
gauss_prime_seeding.py
======================
Initial subhalo placement by a Gaussian-prime spiral walk.

Motivation
----------
The initial positions of subhalo progenitors in a cosmological
patch should avoid artificial lattice symmetries while remaining
reproducible.  We use the Gaussian-prime spiral of Bourke et al.
as a deterministic pseudo-random walk in the complex plane:

    c in Z[i]  is a Gaussian prime iff
      * a = 0 and |b| is prime with |b| = 3 (mod 4), or
      * b = 0 and |a| is prime with |a| = 3 (mod 4), or
      * neither a nor b is zero and a^2 + b^2 is prime.

Starting from a Gaussian integer c_0 and a direction d in {1, i, -1, -i},
the walk increments c by d at each step and rotates d by 90 degrees
(multiplies by i) whenever the new c is a Gaussian prime.  The
resulting trajectory provides a structured yet aperiodic set of
seed positions for subhaloes.

We lift the 2D trajectory to 3D by assigning the z-coordinate
from the imaginary part of the squared Gaussian integer, giving
a quasi-fractal vertical distribution.
"""

from __future__ import annotations
import math
import random
from typing import List, Tuple

import numpy as np


# ---------- Gaussian primality -----------------------------------------------

def _is_rational_prime(n: int) -> bool:
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    r = int(math.isqrt(n))
    for k in range(3, r + 1, 2):
        if n % k == 0:
            return False
    return True


def is_gaussian_prime(a: int, b: int) -> bool:
    """Decide whether a + b i is a Gaussian prime."""
    if a == 0:
        return _is_rational_prime(abs(b)) and (abs(b) % 4 == 3)
    if b == 0:
        return _is_rational_prime(abs(a)) and (abs(a) % 4 == 3)
    return _is_rational_prime(a * a + b * b)


# ---------- Spiral walk ------------------------------------------------------

def gaussian_prime_spiral_step(c: complex, d: complex
                               ) -> Tuple[complex, complex]:
    """Advance the spiral by one step."""
    c_next = c + d
    if is_gaussian_prime(int(c_next.real), int(c_next.imag)):
        d_next = d * 1j            # rotate 90 degrees
    else:
        d_next = d
    return c_next, d_next


def gaussian_prime_spiral_trajectory(c0: complex, d0: complex,
                                     n_steps: int) -> List[complex]:
    """Generate the spiral trajectory starting at c0 with direction d0."""
    traj = [c0]
    c, d = c0, d0
    for _ in range(n_steps - 1):
        c, d = gaussian_prime_spiral_step(c, d)
        traj.append(c)
        if c == c0:
            break
    return traj


# ---------- Lifting to 3D subhalo positions ----------------------------------

def lift_to_3d(traj: List[complex], scale: float = 0.1) -> np.ndarray:
    """Map a complex trajectory to 3D positions.

    (x, y, z) = (Re(c)*scale, Im(c)*scale, Re(c^2) * scale / 10).
    The z coordinate is chosen to break planarity while remaining
    deterministic and reproducible."""
    pts = np.zeros((len(traj), 3))
    for k, c in enumerate(traj):
        a, b = c.real, c.imag
        pts[k, 0] = a * scale
        pts[k, 1] = b * scale
        pts[k, 2] = (a * a - b * b) * scale * 0.1
    return pts


# ---------- Public interface --------------------------------------------------

def seed_subhalo_positions(n_sub: int = 32,
                           c0: complex = 10 + 0j,
                           d0: complex = 1 + 0j,
                           scale: float = 0.05,
                           seed: int = 2024) -> np.ndarray:
    """Return a (n_sub x 3) array of subhalo positions generated by
    the Gaussian-prime spiral.  If the spiral closes before n_sub
    points, we continue with a small random perturbation seeded by
    ``seed``."""
    rng = np.random.default_rng(seed)
    traj = gaussian_prime_spiral_trajectory(c0, d0, max(n_sub, 4 * n_sub))
    if len(traj) < n_sub:
        # pad by jittering the last few points
        extra = []
        while len(traj) + len(extra) < n_sub:
            base = rng.choice(traj)
            jitter = (rng.normal(0, 0.5) + 1j * rng.normal(0, 0.5))
            extra.append(base + jitter)
        traj = traj + extra
    pts = lift_to_3d(traj[:n_sub], scale=scale)
    return pts


# ---------- Self-check --------------------------------------------------------

def self_check() -> dict:
    traj = gaussian_prime_spiral_trajectory(10 + 0j, 1 + 0j, 50)
    pts = seed_subhalo_positions(n_sub=20)
    return dict(traj_len=len(traj),
                pts_shape=list(pts.shape),
                first_point=pts[0].tolist())
