
import numpy as np
from typing import List, Tuple, Optional


def matrix_chain_optimal_order(dims: List[int]) -> Tuple[int, np.ndarray]:
    dims = [int(d) for d in dims]
    n = len(dims) - 1

    if n < 1:
        return 0, np.zeros((0, 0), dtype=np.int64)
    if any(d <= 0 for d in dims):
        raise ValueError("all dimensions must be positive")


    m = np.full((n, n), np.inf, dtype=np.float64)
    s = np.zeros((n, n), dtype=np.int64)

    for i in range(n):
        m[i, i] = 0.0

    for length in range(2, n + 1):
        for i in range(n - length + 1):
            j = i + length - 1
            for k in range(i, j):
                cost = m[i, k] + m[k + 1, j] + dims[i] * dims[k + 1] * dims[j + 1]
                if cost < m[i, j]:
                    m[i, j] = cost
                    s[i, j] = k

    return int(round(m[0, n - 1])), s


def build_optimal_parenthesization(s: np.ndarray, i: int, j: int) -> str:
    if i == j:
        return f"A{i+1}"
    else:
        left = build_optimal_parenthesization(s, i, s[i, j])
        right = build_optimal_parenthesization(s, s[i, j] + 1, j)
        return f"({left} × {right})"


def catalan_number(n: int) -> int:
    if n < 0:
        return 0
    c = 1
    for i in range(1, n + 1):
        c = (c * 2 * (2 * i - 1)) // (i + 1)
    return c


def assemble_enm_stiffness_matrix(
    coords: np.ndarray,
    cutoff: float = 15.0,
    spring_constant: float = 1.0,
) -> np.ndarray:
    coords = np.asarray(coords, dtype=np.float64)
    n_nodes = coords.shape[0]

    if n_nodes < 2:
        raise ValueError("need at least 2 nodes")

    H = np.zeros((3 * n_nodes, 3 * n_nodes), dtype=np.float64)


    for i in range(n_nodes):
        for j in range(i + 1, n_nodes):
            dr = coords[j, :] - coords[i, :]
            r = np.linalg.norm(dr)

            if r < cutoff and r > 1e-6:

                e = dr / r


                block = spring_constant * np.outer(e, e)


                for a in range(3):
                    for b in range(3):
                        idx_i = 3 * i + a
                        idx_j = 3 * j + b
                        H[idx_i, idx_i] += block[a, b]
                        H[idx_j, idx_j] += block[a, b]
                        H[idx_i, idx_j] -= block[a, b]
                        H[idx_j, idx_i] -= block[a, b]

    return H


def write_matrix_market(
    filename: str,
    A: np.ndarray,
    rep: str = "coordinate",
    field: str = "real",
    symm: str = "general",
) -> None:
    A = np.asarray(A, dtype=np.float64)
    m, n = A.shape

    with open(filename, 'w') as f:
        f.write(f"%%MatrixMarket matrix {rep} {field} {symm}\n")
        f.write(f"% Generated by DNA damage repair MD simulation\n")

        if rep == "coordinate":

            rows_list, cols_list = np.nonzero(np.abs(A) > 1e-14)
            if symm in ("symmetric", "hermitian", "skew-symmetric"):
                mask = rows_list >= cols_list
                rows_list = rows_list[mask]
                cols_list = cols_list[mask]
            entries = len(rows_list)
            f.write(f"{m} {n} {entries}\n")
            for i, j in zip(rows_list, cols_list):
                f.write(f"{i+1} {j+1} {A[i, j]:.16e}\n")
        elif rep == "array":
            entries = m * n
            f.write(f"{m} {n}\n")

            for j in range(n):
                for i in range(m):
                    f.write(f"{A[i, j]:.16e}\n")
        else:
            raise ValueError("rep must be 'coordinate' or 'array'")


def read_matrix_market(filename: str) -> Tuple[np.ndarray, int, int, int, str, str, str]:
    with open(filename, 'r') as f:
        lines = f.readlines()


    header = lines[0].strip()
    parts = header.split()
    if len(parts) < 5 or parts[0] != "%%MatrixMarket" or parts[1] != "matrix":
        raise ValueError("invalid Matrix Market header")

    rep = parts[2].lower()
    field = parts[3].lower()
    symm = parts[4].lower()


    idx = 1
    while idx < len(lines) and lines[idx].strip().startswith('%'):
        idx += 1

    if rep == "coordinate":
        size_info = list(map(int, lines[idx].strip().split()))
        rows, cols, entries = size_info[0], size_info[1], size_info[2]
        idx += 1

        A = np.zeros((rows, cols), dtype=np.float64)
        for line in lines[idx:]:
            line = line.strip()
            if not line:
                continue
            tokens = line.split()
            if len(tokens) < 3:
                continue
            i, j = int(tokens[0]) - 1, int(tokens[1]) - 1
            val = float(tokens[2])
            A[i, j] = val


        if symm == "symmetric":
            A = A + A.T - np.diag(np.diag(A))
        elif symm == "skew-symmetric":
            A = A - A.T

    elif rep == "array":
        size_info = list(map(int, lines[idx].strip().split()))
        rows, cols = size_info[0], size_info[1]
        entries = rows * cols
        idx += 1

        values = []
        for line in lines[idx:]:
            line = line.strip()
            if not line:
                continue
            values.append(float(line))

        A = np.array(values, dtype=np.float64).reshape((rows, cols), order='F')

        if symm == "symmetric":
            A = A + A.T - np.diag(np.diag(A))
        elif symm == "skew-symmetric":
            A = A - A.T
    else:
        raise ValueError(f"unsupported representation: {rep}")

    return A, rows, cols, entries, rep, field, symm


def compute_optimal_tensor_contraction_cost(
    tensor_dims: List[Tuple[int, ...]],
    contraction_indices: List[Tuple[int, int]],
) -> int:

    n = len(tensor_dims)
    if n < 2:
        return 0


    dims = [tensor_dims[0][0]]
    for t in tensor_dims:
        if len(t) >= 2:
            dims.append(t[1])
        else:
            dims.append(t[0])

    cost, _ = matrix_chain_optimal_order(dims)
    return cost
