
import numpy as np
from typing import Tuple, List


class SparseMatrix:

    def __init__(self, nrow: int, ncol: int):
        self.nrow = nrow
        self.ncol = ncol
        self.rows: List[int] = []
        self.cols: List[int] = []
        self.vals: List[float] = []

    def add(self, i: int, j: int, v: float) -> None:
        if i < 0 or i >= self.nrow or j < 0 or j >= self.ncol:
            raise IndexError(f"索引 ({i},{j}) 超出矩阵维度 ({self.nrow},{self.ncol})")
        self.rows.append(i)
        self.cols.append(j)
        self.vals.append(v)

    def to_dense(self) -> np.ndarray:
        A = np.zeros((self.nrow, self.ncol))
        for i, j, v in zip(self.rows, self.cols, self.vals):
            A[i, j] += v
        return A

    def to_coo_arrays(self) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        return np.array(self.rows), np.array(self.cols), np.array(self.vals)

    def nnz(self) -> int:
        return len(self.rows)


def build_drift_diffusion_jacobian(
    N: int,
    dx: float,
    mu_n: float,
    mu_p: float,
    D_n: float,
    D_p: float,
    E_field: np.ndarray,
    n: np.ndarray,
    p: np.ndarray,
    kT_q: float,
) -> SparseMatrix:
    if N <= 2:
        raise ValueError("格点数必须大于 2")
    if dx <= 0:
        raise ValueError("网格间距必须为正")

    jac = SparseMatrix(3 * N, 3 * N)


    for i in range(1, N - 1):



        dphi = E_field[i] * dx / kT_q if kT_q != 0 else 0.0
        B_plus = _bernoulli(dphi)
        B_minus = _bernoulli(-dphi)

        coeff = D_n / (dx * dx)

        jac.add(N + i, i, coeff * B_plus)

        jac.add(N + i, i - 1, -coeff * B_minus)

        jac.add(N + i, i + 1, -coeff * B_plus)

        jac.add(N + i, 2 * N + i, 1.0e-10)


    for i in range(1, N - 1):
        dphi = E_field[i] * dx / kT_q if kT_q != 0 else 0.0
        B_plus = _bernoulli(dphi)
        B_minus = _bernoulli(-dphi)

        coeff = D_p / (dx * dx)

        jac.add(2 * N + i, N + i, coeff * B_plus)

        jac.add(2 * N + i, N + i - 1, -coeff * B_minus)

        jac.add(2 * N + i, N + i + 1, -coeff * B_plus)
        jac.add(2 * N + i, 2 * N + i, 1.0e-10)


    eps = 1.0e-12
    for i in range(1, N - 1):

        jac.add(i, 2 * N + i - 1, 1.0 / (dx * dx))
        jac.add(i, 2 * N + i, -2.0 / (dx * dx))
        jac.add(i, 2 * N + i + 1, 1.0 / (dx * dx))

        jac.add(i, i, -1.0 / eps)
        jac.add(i, N + i, 1.0 / eps)


    for i in [0, N - 1]:
        jac.add(N + i, i, 1.0)
        jac.add(2 * N + i, N + i, 1.0)
        jac.add(i, 2 * N + i, 1.0)

    return jac


def _bernoulli(x: float) -> float:
    if abs(x) < 1e-5:
        return 1.0 - x / 2.0 + x * x / 12.0
    elif x > 20.0:
        return x * np.exp(-x)
    elif x < -20.0:
        return -x
    else:
        return x / (np.exp(x) - 1.0)


def write_matrix_market(A: SparseMatrix, filename: str, symm: str = "general") -> None:
    with open(filename, 'w') as f:
        f.write("%%MatrixMarket matrix coordinate real {}\n".format(symm))
        f.write("% Generated by sparse_matrix_io.py for perovskite solar cell\n")
        f.write("{} {} {}\n".format(A.nrow, A.ncol, A.nnz()))
        for i, j, v in zip(A.rows, A.cols, A.vals):
            f.write("{} {} {:.16e}\n".format(i + 1, j + 1, v))


def read_matrix_market(filename: str) -> SparseMatrix:
    with open(filename, 'r') as f:
        lines = f.readlines()


    idx = 0
    while lines[idx].strip().startswith('%'):
        idx += 1

    header = lines[idx].strip().split()
    nrow, ncol, nnz_expected = int(header[0]), int(header[1]), int(header[2])
    A = SparseMatrix(nrow, ncol)

    for line in lines[idx + 1:]:
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        i, j, v = int(parts[0]) - 1, int(parts[1]) - 1, float(parts[2])
        A.add(i, j, v)

    if A.nnz() != nnz_expected:

        pass
    return A


if __name__ == "__main__":
    N = 10
    dx = 1e-6
    E = np.zeros(N)
    n = np.ones(N) * 1e15
    p = np.ones(N) * 1e15
    jac = build_drift_diffusion_jacobian(N, dx, 20.0, 10.0, 0.5, 0.25, E, n, p, 0.0259)
    print(f"Jacobian 维度: {jac.nrow}×{jac.ncol}, 非零元: {jac.nnz()}")
    fname = "/mnt/data/zpy/sci-swe/source code/Synthesis-project-python/161_synth_project/test_jac.mtx"
    write_matrix_market(jac, fname)
    A2 = read_matrix_market(fname)
    print(f"读取后非零元: {A2.nnz()}")
    import os
    os.remove(fname)
