"""
obj_io.py
=========
基于种子项目 822_obj_io 的 Wavefront OBJ 文件 I/O 模块。
提供 3D 网格（顶点、面片、法向量）的读写功能，
用于物理信息 GAN 中三维流场域边界的持久化与复用。

核心数学：
  1. OBJ 文件格式：
       v x y z          — 几何顶点
       vn nx ny nz      — 顶点法线
       f v1 v2 v3 ...   — 面片（顶点索引，1-based）
       f v1//vn1 v2//vn2 ... — 含法线索引的面片

  2. 面片法向量计算：
       n = (v2 - v1) × (v3 - v1) / ||(v2 - v1) × (v3 - v1)||

  3. 顶点法线平均：
       对于共享顶点，将其所在所有面片的法向量按面积加权平均后归一化。
"""

import numpy as np


def r8vec_cross_3d(v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
    """三维向量叉积。"""
    v1 = np.asarray(v1, dtype=float)
    v2 = np.asarray(v2, dtype=float)
    return np.array([
        v1[1] * v2[2] - v1[2] * v2[1],
        v1[2] * v2[0] - v1[0] * v2[2],
        v1[0] * v2[1] - v1[1] * v2[0],
    ])


def obj_read(input_file_name: str) -> dict:
    """
    读取 Wavefront OBJ 文件。

    Parameters
    ----------
    input_file_name : str
        OBJ 文件路径。

    Returns
    -------
    data : dict
        {'vertices': np.ndarray, 'normals': np.ndarray, 'faces': list}
    """
    vertices = []
    normals = []
    faces = []
    with open(input_file_name, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if not parts:
                continue
            keyword = parts[0].upper()
            if keyword == 'V' and len(parts) >= 4:
                vertices.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif keyword == 'VN' and len(parts) >= 4:
                normals.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif keyword == 'F':
                face = []
                for part in parts[1:]:
                    # 支持 v/vt/vn 或 v//vn 格式
                    indices = part.split('/')
                    v_idx = int(indices[0]) - 1  # 转为 0-based
                    face.append(v_idx)
                faces.append(face)

    return {
        "vertices": np.array(vertices, dtype=float) if vertices else np.zeros((0, 3)),
        "normals": np.array(normals, dtype=float) if normals else np.zeros((0, 3)),
        "faces": faces,
    }


def obj_write(output_file_name: str, vertices: np.ndarray,
              faces: list, normals: np.ndarray = None) -> None:
    """
    写入 Wavefront OBJ 文件。

    Parameters
    ----------
    output_file_name : str
        输出文件路径。
    vertices : np.ndarray, shape (n, 3)
        顶点坐标。
    faces : list of list
        面片顶点索引（0-based 内部存储，输出转为 1-based）。
    normals : np.ndarray, shape (m, 3), optional
        顶点法线。
    """
    with open(output_file_name, 'w', encoding='utf-8') as f:
        f.write("# Generated by Physics-Informed GAN synthesis project\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        if normals is not None and len(normals) > 0:
            for n in normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        for face in faces:
            # 简单输出顶点索引（1-based）
            indices = ' '.join(str(idx + 1) for idx in face)
            f.write(f"f {indices}\n")


def compute_face_normals(vertices: np.ndarray, faces: list) -> np.ndarray:
    """
    计算所有面片的单位法向量。

    Returns
    -------
    face_normals : np.ndarray, shape (m, 3)
    """
    fn = []
    for face in faces:
        if len(face) < 3:
            fn.append([0.0, 0.0, 1.0])
            continue
        v1 = vertices[face[0]]
        v2 = vertices[face[1]]
        v3 = vertices[face[2]]
        cross = r8vec_cross_3d(v2 - v1, v3 - v1)
        norm = np.linalg.norm(cross)
        if norm < 1e-15:
            fn.append([0.0, 0.0, 1.0])
        else:
            fn.append(cross / norm)
    return np.array(fn, dtype=float)


def compute_vertex_normals(vertices: np.ndarray, faces: list) -> np.ndarray:
    """
    计算顶点法线（共享面法线的面积加权平均）。

    Returns
    -------
    vertex_normals : np.ndarray, shape (n, 3)
    """
    n = vertices.shape[0]
    vn = np.zeros((n, 3))
    counts = np.zeros(n)
    for face in faces:
        if len(face) < 3:
            continue
        v1 = vertices[face[0]]
        v2 = vertices[face[1]]
        v3 = vertices[face[2]]
        cross = r8vec_cross_3d(v2 - v1, v3 - v1)
        area = 0.5 * np.linalg.norm(cross)
        norm = np.linalg.norm(cross)
        if norm < 1e-15:
            continue
        fn = cross / norm
        for idx in face:
            vn[idx] += area * fn
            counts[idx] += area
    counts = np.where(counts < 1e-15, 1.0, counts)
    vn = vn / counts[:, None]
    norms = np.linalg.norm(vn, axis=1, keepdims=True)
    norms = np.where(norms < 1e-15, 1.0, norms)
    return vn / norms


def icosphere_obj(radius: float = 1.0, subdivisions: int = 1) -> tuple:
    """
    生成 icosphere 网格并返回顶点与面片。

    Parameters
    ----------
    radius : float
        球体半径。
    subdivisions : int
        细分次数（0 为正二十面体，1 为细分一次，以此类推）。

    Returns
    -------
    vertices : np.ndarray
    faces : list
    """
    from sphere_quad import icosahedron_faces
    faces_idx, vertices = icosahedron_faces()
    faces = [list(f) for f in faces_idx]

    def midpoint(v1, v2):
        return (v1 + v2) / 2.0

    for _ in range(subdivisions):
        new_faces = []
        edge_map = {}
        def get_mid(i, j):
            key = (min(i, j), max(i, j))
            if key not in edge_map:
                edge_map[key] = len(vertices)
                vertices = np.vstack([vertices, midpoint(vertices[key[0]], vertices[key[1]])])
            return edge_map[key]

        # 重新获取 vertices 引用（因为闭包中需要可变引用）
        # 这里用循环外局部变量避免闭包问题
        current_vertices = vertices
        edge_map_local = {}
        new_verts = list(current_vertices)

        def get_mid_local(i, j):
            key = (min(i, j), max(i, j))
            if key not in edge_map_local:
                edge_map_local[key] = len(new_verts)
                new_verts.append((current_vertices[i] + current_vertices[j]) / 2.0)
            return edge_map_local[key]

        for face in faces:
            i, j, k = face
            a = get_mid_local(i, j)
            b = get_mid_local(j, k)
            c = get_mid_local(k, i)
            new_faces.append([i, a, c])
            new_faces.append([j, b, a])
            new_faces.append([k, c, b])
            new_faces.append([a, b, c])

        vertices = np.array(new_verts, dtype=float)
        # 归一化到球面
        norms = np.linalg.norm(vertices, axis=1, keepdims=True)
        norms = np.where(norms < 1e-15, 1.0, norms)
        vertices = vertices / norms * radius
        faces = new_faces

    return vertices, faces
