
import numpy as np


def r8vec_cross_3d(v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
    v1 = np.asarray(v1, dtype=float)
    v2 = np.asarray(v2, dtype=float)
    return np.array([
        v1[1] * v2[2] - v1[2] * v2[1],
        v1[2] * v2[0] - v1[0] * v2[2],
        v1[0] * v2[1] - v1[1] * v2[0],
    ])


def obj_read(input_file_name: str) -> dict:
    vertices = []
    normals = []
    faces = []
    with open(input_file_name, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if not parts:
                continue
            keyword = parts[0].upper()
            if keyword == 'V' and len(parts) >= 4:
                vertices.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif keyword == 'VN' and len(parts) >= 4:
                normals.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif keyword == 'F':
                face = []
                for part in parts[1:]:

                    indices = part.split('/')
                    v_idx = int(indices[0]) - 1
                    face.append(v_idx)
                faces.append(face)

    return {
        "vertices": np.array(vertices, dtype=float) if vertices else np.zeros((0, 3)),
        "normals": np.array(normals, dtype=float) if normals else np.zeros((0, 3)),
        "faces": faces,
    }


def obj_write(output_file_name: str, vertices: np.ndarray,
              faces: list, normals: np.ndarray = None) -> None:
    with open(output_file_name, 'w', encoding='utf-8') as f:
        f.write("# Generated by Physics-Informed GAN synthesis project\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        if normals is not None and len(normals) > 0:
            for n in normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        for face in faces:

            indices = ' '.join(str(idx + 1) for idx in face)
            f.write(f"f {indices}\n")


def compute_face_normals(vertices: np.ndarray, faces: list) -> np.ndarray:
    fn = []
    for face in faces:
        if len(face) < 3:
            fn.append([0.0, 0.0, 1.0])
            continue
        v1 = vertices[face[0]]
        v2 = vertices[face[1]]
        v3 = vertices[face[2]]
        cross = r8vec_cross_3d(v2 - v1, v3 - v1)
        norm = np.linalg.norm(cross)
        if norm < 1e-15:
            fn.append([0.0, 0.0, 1.0])
        else:
            fn.append(cross / norm)
    return np.array(fn, dtype=float)


def compute_vertex_normals(vertices: np.ndarray, faces: list) -> np.ndarray:
    n = vertices.shape[0]
    vn = np.zeros((n, 3))
    counts = np.zeros(n)
    for face in faces:
        if len(face) < 3:
            continue
        v1 = vertices[face[0]]
        v2 = vertices[face[1]]
        v3 = vertices[face[2]]
        cross = r8vec_cross_3d(v2 - v1, v3 - v1)
        area = 0.5 * np.linalg.norm(cross)
        norm = np.linalg.norm(cross)
        if norm < 1e-15:
            continue
        fn = cross / norm
        for idx in face:
            vn[idx] += area * fn
            counts[idx] += area
    counts = np.where(counts < 1e-15, 1.0, counts)
    vn = vn / counts[:, None]
    norms = np.linalg.norm(vn, axis=1, keepdims=True)
    norms = np.where(norms < 1e-15, 1.0, norms)
    return vn / norms


def icosphere_obj(radius: float = 1.0, subdivisions: int = 1) -> tuple:
    from sphere_quad import icosahedron_faces
    faces_idx, vertices = icosahedron_faces()
    faces = [list(f) for f in faces_idx]

    def midpoint(v1, v2):
        return (v1 + v2) / 2.0

    for _ in range(subdivisions):
        new_faces = []
        edge_map = {}
        def get_mid(i, j):
            key = (min(i, j), max(i, j))
            if key not in edge_map:
                edge_map[key] = len(vertices)
                vertices = np.vstack([vertices, midpoint(vertices[key[0]], vertices[key[1]])])
            return edge_map[key]



        current_vertices = vertices
        edge_map_local = {}
        new_verts = list(current_vertices)

        def get_mid_local(i, j):
            key = (min(i, j), max(i, j))
            if key not in edge_map_local:
                edge_map_local[key] = len(new_verts)
                new_verts.append((current_vertices[i] + current_vertices[j]) / 2.0)
            return edge_map_local[key]

        for face in faces:
            i, j, k = face
            a = get_mid_local(i, j)
            b = get_mid_local(j, k)
            c = get_mid_local(k, i)
            new_faces.append([i, a, c])
            new_faces.append([j, b, a])
            new_faces.append([k, c, b])
            new_faces.append([a, b, c])

        vertices = np.array(new_verts, dtype=float)

        norms = np.linalg.norm(vertices, axis=1, keepdims=True)
        norms = np.where(norms < 1e-15, 1.0, norms)
        vertices = vertices / norms * radius
        faces = new_faces

    return vertices, faces
