"""
output_diagnostics.py - 模拟数据输出与诊断分析

本模块融合以下种子项目的核心算法：
  - 351_fd_to_tec → 数据格式化输出
  - 1109_marekgluza_Fidelity_witnesses_example → 状态保真度追踪

功能：
  1. 结构化ASCII数据输出
  2. 收敛历史追踪
  3. 误差与保真度计算
  4. 物理量诊断
  5. 模拟摘要报告
"""

import numpy as np
import os
from typing import Dict, List, Optional, Tuple
from plasma_physics import (
    plasma_state_fidelity, L2_error_norm, H1_seminorm,
    divertor_target_heat_flux, sound_speed, EV_TO_JOULE
)


# =============================================================================
# 数据输出格式化（来自351_fd_to_tec）
# =============================================================================
def write_ascii_data(filename: str, headers: List[str],
                       data: np.ndarray, title: str = "Simulation Output"):
    """
    将模拟数据写入ASCII文件

    格式类似TECPLOT ASCII，但简化为纯文本格式

    参数:
        filename: 输出文件名
        headers: 列标题
        data: shape (n_rows, n_cols) 数据矩阵
        title: 标题
    """
    with open(filename, 'w') as f:
        f.write(f"# {title}\n")
        f.write(f"# Generated by edge_plasma_divertor_transport\n")
        f.write(f"# Columns: {', '.join(headers)}\n")
        f.write(f"# Rows: {data.shape[0]}\n")
        f.write("#" + "-" * 60 + "\n")

        for row in data:
            line = "  ".join(f"{v:16.8e}" for v in row)
            f.write(line + "\n")


def write_simulation_summary(filename: str, summary: Dict):
    """
    写入模拟摘要报告

    参数:
        filename: 输出文件名
        summary: 摘要字典
    """
    with open(filename, 'w') as f:
        f.write("=" * 70 + "\n")
        f.write(" 边界等离子体输运与偏滤器热负荷模拟 - 摘要报告\n")
        f.write(" Edge Plasma Transport & Divertor Heat Flux Simulation Summary\n")
        f.write("=" * 70 + "\n\n")

        for key, value in summary.items():
            if isinstance(value, float):
                f.write(f"  {key:40s}: {value:16.8e}\n")
            elif isinstance(value, int):
                f.write(f"  {key:40s}: {value:10d}\n")
            elif isinstance(value, str):
                f.write(f"  {key:40s}: {value}\n")
            elif isinstance(value, dict):
                f.write(f"\n  [{key}]\n")
                for k2, v2 in value.items():
                    if isinstance(v2, float):
                        f.write(f"    {k2:38s}: {v2:16.8e}\n")
                    else:
                        f.write(f"    {k2:38s}: {v2}\n")
            elif isinstance(value, np.ndarray):
                f.write(f"  {key:40s}: array shape={value.shape}\n")
            else:
                f.write(f"  {key:40s}: {value}\n")

        f.write("\n" + "=" * 70 + "\n")


# =============================================================================
# 收敛历史追踪
# =============================================================================
class ConvergenceTracker:
    """
    追踪迭代求解器的收敛历史
    """

    def __init__(self):
        self.iterations = []
        self.residuals = []
        self.fidelities = []
        self.errors_L2 = []
        self.errors_H1 = []
        self.mass_errors = []

    def record(self, iteration: int, residual: float,
                fidelity: float = None, error_L2: float = None,
                error_H1: float = None, mass_error: float = None):
        """记录一步的收敛数据"""
        self.iterations.append(iteration)
        self.residuals.append(residual)
        if fidelity is not None:
            self.fidelities.append(fidelity)
        if error_L2 is not None:
            self.errors_L2.append(error_L2)
        if error_H1 is not None:
            self.errors_H1.append(error_H1)
        if mass_error is not None:
            self.mass_errors.append(mass_error)

    def get_convergence_rate(self) -> float:
        """
        估计收敛速率

        rate ≈ log(r_n / r_0) / n
        """
        if len(self.residuals) < 2:
            return 0.0

        r0 = self.residuals[0]
        rn = self.residuals[-1]
        n = len(self.residuals) - 1

        if r0 < 1e-30 or rn < 1e-30:
            return 0.0

        rate = np.log(rn / r0) / n
        return float(rate)

    def to_dict(self) -> Dict:
        """转换为字典"""
        return {
            'iterations': np.array(self.iterations),
            'residuals': np.array(self.residuals),
            'fidelities': np.array(self.fidelities) if self.fidelities else None,
            'errors_L2': np.array(self.errors_L2) if self.errors_L2 else None,
            'errors_H1': np.array(self.errors_H1) if self.errors_H1 else None,
            'mass_errors': np.array(self.mass_errors) if self.mass_errors else None,
        }

    def write_to_file(self, filename: str):
        """写入收敛历史到文件"""
        data = np.column_stack([
            np.array(self.iterations),
            np.array(self.residuals),
        ])
        headers = ['iteration', 'residual']
        write_ascii_data(filename, headers, data, "Convergence History")


# =============================================================================
# 物理诊断量计算
# =============================================================================
def compute_plasma_diagnostics(n_profile: np.ndarray,
                                 T_profile: np.ndarray,
                                 R_grid: np.ndarray,
                                 B_field: float = 5.3) -> Dict:
    """
    计算等离子体诊断量

    参数:
        n_profile: 密度剖面 [m^-3]
        T_profile: 温度剖面 [eV]
        R_grid: 径向网格 [m]
        B_field: 磁场强度 [T]
    返回:
        dict包含各种诊断量
    """
    # 声速剖面
    c_s = np.array([sound_speed(T, T) for T in T_profile])

    # 热流密度剖面（简化）
    # q = -kappa * dT/dR
    dT_dR = np.gradient(T_profile, R_grid)

    # 近似Spitzer热传导
    from plasma_physics import spitzer_harm_conductivity
    kappa_profile = np.zeros_like(T_profile)
    for i in range(len(T_profile)):
        if T_profile[i] > 0.1 and n_profile[i] > 1e15:
            kappa_profile[i] = spitzer_harm_conductivity(n_profile[i], T_profile[i])

    q_profile = -kappa_profile * dT_dR  # W/m² (每eV温度梯度)

    # 等离子体储存能量
    # W = integral(3/2 * n * T * dV)
    # 简化为一维：W = integral(3 * n * T * 2*pi*R * dR) (包含电子和离子)
    integrand = 3.0 * n_profile * T_profile * EV_TO_JOULE * 2.0 * np.pi * R_grid
    stored_energy = np.trapz(integrand, R_grid)  # J/m

    # 粒子数
    N_particles = np.trapz(n_profile * 2.0 * np.pi * R_grid, R_grid)  # m^-2

    # 靶板热负荷（使用最后一个点）
    n_target = n_profile[-1]
    T_target = T_profile[-1]
    q_target = divertor_target_heat_flux(n_target, T_target)

    return {
        'c_s_max': float(np.max(c_s)),
        'c_s_min': float(np.min(c_s)),
        'q_max': float(np.max(np.abs(q_profile))),
        'stored_energy': float(stored_energy),
        'total_particles': float(N_particles),
        'q_target': float(q_target),
        'n_peak': float(np.max(n_profile)),
        'T_peak': float(np.max(T_profile)),
        'kappa_max': float(np.max(kappa_profile)),
        'B_field': B_field,
    }


# =============================================================================
# 保真度与误差度量
# =============================================================================
def compute_solution_quality(solution: np.ndarray,
                               reference: np.ndarray,
                               dx: float = 1.0) -> Dict:
    """
    计算数值解的质量指标

    参数:
        solution: 数值解
        reference: 参考解（解析或高精度）
        dx: 网格间距
    返回:
        dict包含各种误差度量
    """
    fidelity = plasma_state_fidelity(solution, reference)
    L2 = L2_error_norm(solution, reference, dx)
    H1 = H1_seminorm(solution, reference, dx)

    # 相对L2误差
    ref_norm = np.sqrt(np.sum(reference**2) * dx)
    if ref_norm > 1e-30:
        rel_L2 = L2 / ref_norm
    else:
        rel_L2 = 0.0

    # 最大值误差
    max_err = np.max(np.abs(solution - reference))

    # 质量守恒（假设守恒量是积分）
    mass_computed = np.sum(solution) * dx
    mass_reference = np.sum(reference) * dx
    if abs(mass_reference) > 1e-30:
        mass_error = abs(mass_computed - mass_reference) / abs(mass_reference)
    else:
        mass_error = 0.0

    return {
        'fidelity': float(fidelity),
        'L2_error': float(L2),
        'H1_error': float(H1),
        'relative_L2': float(rel_L2),
        'max_error': float(max_err),
        'mass_conservation_error': float(mass_error),
    }


# =============================================================================
# 模拟报告生成
# =============================================================================
def generate_final_report(results: Dict) -> str:
    """
    生成文本格式的模拟报告

    参数:
        results: 所有模拟结果的字典
    返回:
        report: 报告文本
    """
    lines = []
    lines.append("=" * 70)
    lines.append(" 边界等离子体输运与偏滤器热负荷 - 最终模拟报告")
    lines.append(" High-Order Finite Difference & Stability Analysis")
    lines.append("=" * 70)
    lines.append("")

    # 物理参数
    if 'physics_params' in results:
        lines.append("[物理参数]")
        for k, v in results['physics_params'].items():
            if isinstance(v, float):
                lines.append(f"  {k:30s}: {v:.6e}")
            else:
                lines.append(f"  {k:30s}: {v}")
        lines.append("")

    # 数值方法
    if 'numerical_params' in results:
        lines.append("[数值方法]")
        for k, v in results['numerical_params'].items():
            lines.append(f"  {k:30s}: {v}")
        lines.append("")

    # 稳定性分析
    if 'stability' in results:
        lines.append("[稳定性分析]")
        for k, v in results['stability'].items():
            if isinstance(v, float):
                lines.append(f"  {k:30s}: {v:.6e}")
            elif isinstance(v, bool):
                lines.append(f"  {k:30s}: {'Yes' if v else 'No'}")
            else:
                lines.append(f"  {k:30s}: {v}")
        lines.append("")

    # 收敛信息
    if 'convergence' in results:
        lines.append("[收敛信息]")
        conv = results['convergence']
        if 'final_residual' in conv:
            lines.append(f"  {'最终残差':28s}: {conv['final_residual']:.6e}")
        if 'convergence_rate' in conv:
            lines.append(f"  {'收敛速率':28s}: {conv['convergence_rate']:.6e}")
        if 'fidelity' in conv:
            lines.append(f"  {'保真度':28s}: {conv['fidelity']:.6f}")
        lines.append("")

    # 物理结果
    if 'physics_results' in results:
        lines.append("[物理结果]")
        for k, v in results['physics_results'].items():
            if isinstance(v, float):
                lines.append(f"  {k:30s}: {v:.6e}")
            else:
                lines.append(f"  {k:30s}: {v}")
        lines.append("")

    # 参数扫描
    if 'parameter_scan' in results:
        lines.append("[参数扫描结果摘要]")
        ps = results['parameter_scan']
        if 'q_target_mean' in ps:
            lines.append(f"  {'靶板热负荷均值':26s}: {ps['q_target_mean']:.6e} W/m²")
        if 'q_target_std' in ps:
            lines.append(f"  {'靶板热负荷标准差':24s}: {ps['q_target_std']:.6e} W/m²")
        lines.append("")

    lines.append("=" * 70)
    lines.append(" 模拟完成")
    lines.append("=" * 70)

    return "\n".join(lines)
