
import numpy as np


def matrix_to_coordinate_format(A, symmetry='general'):
    A = np.asarray(A)
    n_rows, n_cols = A.shape
    
    rows, cols, vals = [], [], []
    
    for i in range(n_rows):
        j_start = i if symmetry in ('symmetric', 'hermitian') else 0
        if symmetry == 'skew-symmetric':
            j_start = i + 1
        
        for j in range(j_start, n_cols):
            val = A[i, j]
            if abs(val) > 1e-15:
                rows.append(i + 1)
                cols.append(j + 1)
                vals.append(val)
    
    return np.array(rows, dtype=int), np.array(cols, dtype=int), np.array(vals, dtype=float)


def export_matrix_market(filename, A, format_type='coordinate',
                         matrix_type='real', symmetry='general',
                         comment="Structural analysis matrix"):
    A = np.asarray(A)
    n_rows, n_cols = A.shape
    
    with open(filename, 'w') as f:
        f.write(f"%%MatrixMarket matrix {format_type} {matrix_type} {symmetry}\n")
        f.write(f"% {comment}\n")
        f.write(f"% Generated by Structural Reliability Analysis Framework\n")
        
        if format_type == 'coordinate':
            rows, cols, vals = matrix_to_coordinate_format(A, symmetry)
            n_nonzeros = len(vals)
            f.write(f"{n_rows} {n_cols} {n_nonzeros}\n")
            for i, j, v in zip(rows, cols, vals):
                f.write(f"{i} {j} {v:.16e}\n")
        else:

            f.write(f"{n_rows} {n_cols}\n")
            for i in range(n_rows):
                for j in range(n_cols):
                    f.write(f"{A[i, j]:.16e} ")
                f.write("\n")


def export_structural_matrices(K, M, C=None, prefix="structural"):
    export_matrix_market(f"{prefix}_K.mtx", K, symmetry='symmetric',
                         comment="Global stiffness matrix")
    export_matrix_market(f"{prefix}_M.mtx", M, symmetry='symmetric',
                         comment="Global mass matrix")
    if C is not None:
        export_matrix_market(f"{prefix}_C.mtx", C, symmetry='symmetric',
                             comment="Global damping matrix")


def read_matrix_market(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()
    

    idx = 0
    while lines[idx].startswith('%'):
        idx += 1
    
    header = lines[0].strip()
    parts = header.split()
    symmetry = parts[-1] if len(parts) > 4 else 'general'
    

    dims = lines[idx].strip().split()
    n_rows = int(dims[0])
    n_cols = int(dims[1])
    
    A = np.zeros((n_rows, n_cols))
    
    if 'coordinate' in header:
        n_nz = int(dims[2])
        for line in lines[idx + 1:]:
            if line.strip():
                parts = line.strip().split()
                i, j = int(parts[0]) - 1, int(parts[1]) - 1
                val = float(parts[2])
                A[i, j] = val
                if symmetry in ('symmetric', 'hermitian'):
                    A[j, i] = val
                elif symmetry == 'skew-symmetric':
                    A[j, i] = -val
    else:

        row = 0
        for line in lines[idx + 1:]:
            if line.strip():
                vals = [float(v) for v in line.strip().split()]
                A[row, :len(vals)] = vals
                row += 1
    
    return A
