"""
orthogonal_fit.py
=================
Orthogonal polynomial fitting for spatial representation of rock property fields.

Incorporates algorithms from:
  - 209_conte_deboor: discrete weighted orthogonal polynomial approximation

Mathematical formulation:
Given data points {(x_i, f_i)} with weights {w_i}, we seek a polynomial
approximant p(x) of degree at most N-1 that minimizes the weighted least-squares error:

  \min_p \sum_{i=1}^{M} w_i \left[ f_i - p(x_i) \right]^2

The polynomial is expressed in an orthonormal basis {P_j(x)} generated by the
three-term recurrence:

  P_{j+1}(x) = (x - B_{j+1}) P_j(x) - C_{j+1} P_{j-1}(x)

with P_0(x) = 1, P_{-1}(x) = 0.

The coefficients in the expansion p(x) = \sum_{j=0}^{N-1} D_j P_j(x) are:

  D_j = \frac{(f, P_j)}{(P_j, P_j)} = \frac{\sum_i w_i f_i P_j(x_i)}{\sum_i w_i P_j^2(x_i)}

The discrete inner product is defined as:
  (u, v) = \sum_{i=1}^{M} w_i u(x_i) v(x_i)
"""

import numpy as np


class OrthogonalPolynomialFit:
    """
    Weighted least-squares polynomial fit using an orthogonal polynomial basis.
    """

    def __init__(self, x_data, f_data, weights, n_terms):
        """
        Parameters
        ----------
        x_data : np.ndarray, shape (M,)
            Abscissae.
        f_data : np.ndarray, shape (M,)
            Ordinates.
        weights : np.ndarray, shape (M,)
            Weights for the discrete inner product.
        n_terms : int
            Number of terms (degree <= n_terms - 1).
        """
        x_data = np.asarray(x_data, dtype=np.float64)
        f_data = np.asarray(f_data, dtype=np.float64)
        weights = np.asarray(weights, dtype=np.float64)
        n_terms = int(n_terms)

        if x_data.ndim != 1 or f_data.ndim != 1 or weights.ndim != 1:
            raise ValueError("Inputs must be 1-D arrays.")
        if x_data.size != f_data.size or x_data.size != weights.size:
            raise ValueError("x_data, f_data, and weights must have the same length.")
        if n_terms < 1:
            raise ValueError("n_terms must be at least 1.")
        if np.any(weights < 0):
            raise ValueError("Weights must be non-negative.")
        if np.sum(weights) == 0:
            raise ValueError("Sum of weights must be positive.")

        self.x_data = x_data
        self.n_terms = n_terms
        self._fit(x_data, f_data, weights)

    def _fit(self, x, f, w):
        """Build orthogonal basis and compute coefficients."""
        w = w / np.sum(w)  # normalize weights
        x = x.flatten()
        f = f.flatten()
        M = x.size

        # Arrays for recurrence coefficients
        B = np.zeros(self.n_terms)
        C = np.zeros(self.n_terms)
        D = np.zeros(self.n_terms)
        S = np.zeros(self.n_terms)

        # P0
        Pjm1 = np.ones(M)
        S[0] = np.sum(w * Pjm1 ** 2)
        D[0] = np.sum(w * f * Pjm1) / S[0]
        error = f - D[0] * Pjm1

        if self.n_terms == 1:
            self.B = B
            self.C = C
            self.D = D
            self.S = S
            self.residual = error
            return

        # P1
        B[0] = np.sum(w * x) / np.sum(w)
        Pj = x - B[0]
        S[0] = np.sum(w * Pjm1 ** 2)

        P = Pj * w
        D[1] = np.sum(error * Pj) / np.sum(w * Pj ** 2)
        error = error - D[1] * Pj

        for j in range(2, self.n_terms):
            P = Pj * w
            B[j - 1] = np.sum(x * Pj * P) / np.sum(w * Pj ** 2)
            C[j - 1] = np.sum(w * Pj ** 2) / np.sum(w * Pjm1 ** 2)
            S[j - 1] = np.sum(w * Pj ** 2)

            P_new = (x - B[j - 1]) * Pj - C[j - 1] * Pjm1
            D[j] = np.sum(error * P_new) / np.sum(w * P_new ** 2)
            error = error - D[j] * P_new

            Pjm1 = Pj
            Pj = P_new

        S[self.n_terms - 1] = np.sum(w * Pj ** 2)
        self.B = B
        self.C = C
        self.D = D
        self.S = S
        self.residual = error

    def evaluate(self, xq):
        """
        Evaluate the fitted polynomial at query points.

        Parameters
        ----------
        xq : np.ndarray
            Query points.

        Returns
        -------
        yq : np.ndarray
            Fitted values.
        """
        xq = np.asarray(xq, dtype=np.float64)
        M = xq.size
        yq = np.zeros(M)

        Pjm1 = np.ones(M)
        yq += self.D[0] * Pjm1

        if self.n_terms == 1:
            return yq

        Pj = xq - self.B[0]
        yq += self.D[1] * Pj

        for j in range(2, self.n_terms):
            P_new = (xq - self.B[j - 1]) * Pj - self.C[j - 1] * Pjm1
            yq += self.D[j] * P_new
            Pjm1 = Pj
            Pj = P_new

        return yq

    def basis_polynomial(self, xq, j):
        """
        Evaluate the j-th orthonormal basis polynomial at query points.

        Parameters
        ----------
        xq : np.ndarray
            Query points.
        j : int
            Basis index (0 <= j < n_terms).

        Returns
        -------
        Pj : np.ndarray
        """
        if j < 0 or j >= self.n_terms:
            raise ValueError("Invalid basis index.")
        xq = np.asarray(xq, dtype=np.float64)
        M = xq.size
        if j == 0:
            return np.ones(M)
        Pjm1 = np.ones(M)
        Pj = xq - self.B[0]
        if j == 1:
            return Pj
        for k in range(2, j + 1):
            P_new = (xq - self.B[k - 1]) * Pj - self.C[k - 1] * Pjm1
            Pjm1 = Pj
            Pj = P_new
        return Pj


def fit_permeability_field_1d(x, k_data, n_terms=6):
    """
    Fit a 1D permeability field using orthogonal polynomials.

    Parameters
    ----------
    x : np.ndarray
        Spatial coordinates (m).
    k_data : np.ndarray
        Measured permeability values (m^2) or log10(permeability).
    n_terms : int
        Number of polynomial terms.

    Returns
    -------
    OrthogonalPolynomialFit
    """
    # Use uniform weights for robustness
    weights = np.ones_like(x)
    return OrthogonalPolynomialFit(x, k_data, weights, n_terms)


def fit_thermal_conductivity_field_1d(x, lambda_data, n_terms=6):
    """
    Fit a 1D thermal conductivity field using orthogonal polynomials.
    """
    weights = np.ones_like(x)
    return OrthogonalPolynomialFit(x, lambda_data, weights, n_terms)
