# -*- coding: utf-8 -*-
"""
zonal_flow.py
=============

Rosenbluth-Hinton zonal-flow residual calculation.

Zonal flows are radially-localised, poloidally-symmetric (m = n = 0)
E x B flows generated by the Reynolds stress of the turbulence.  They
are the dominant self-regulation mechanism of ITG turbulence and their
residual level controls the saturated transport level.

The canonical test (Rosenbluth & Hinton 1998) is:

    1. Initialise a finite-amplitude zonal potential  phi(x, t=0)
       (typically sinusoidal in x).
    2. Let the system evolve collisionlessly under the gyrokinetic
       equation with all drive terms turned off.
    3. Measure the long-time residual  phi(t -> infty) / phi(0).

The theoretical prediction for the residual in the long-wavelength limit
is (for a circular tokamak with aspect ratio R0/a and safety factor q)

    phi_res / phi_0  =  1 / (1 + 1.6 q^2 / sqrt(epsilon))

where  epsilon = r / R0.  This formula captures the fraction of the
initial potential that is *not* shielded by the passing-ion polarisation
current.

Governing equation
------------------
The vorticity equation in the long-wavelength, electrostatic, collisionless
limit reduces to

    d/dt  [ n_i (1 - Gamma_0) phi / B^2 ]  +  ...
        =  (e n_i / T_i)  (1 - Gamma_0) dphi/dt
          - (e / T_i) int v_parallel^2 C[delta f_i] d^3 v

In the collisionless limit the residual satisfies the steady-state
equation

    (1 + tau_e) (1 - Gamma_0) phi_res  +  n_i chi_pol phi_res  =  RHS

where  chi_pol  is the neoclassical polarisability.  In our 1-D slab
reduction  chi_pol  reduces to a radial second-derivative operator
weighted by the equilibrium density, and the equation becomes a
linear elliptic BVP that we solve with the 1-D FEM of ``radial_mesh``.

References:
    [1] Rosenbluth & Hinton, Phys. Rev. Lett. 80, 724 (1998)
    [2] Hinton & Hazeltine, Rev. Mod. Phys. 48, 239 (1976)
    [3] Winsor et al., Phys. Fluids 11, 2448 (1968)  (the "Winsor
        constant" for the residual).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

from gyroaverage import gamma0, gamma0_pade
from radial_mesh import RadialMesh1D


@dataclass
class ZonalFlowParams:
    """Dimensionless parameters for the residual calculation."""
    tau_e: float = 1.0       # T_e / T_i
    q_safety: float = 2.0    # safety factor
    epsilon: float = 0.3     # inverse aspect ratio  r / R0
    k_x_rho: float = 0.1     # radial wavenumber  k_x rho_s
    Z_i: float = 1.0

    @property
    def b(self) -> float:
        """Argument of Gamma_0:  b = k_perp^2 rho_s^2 / 2."""
        return 0.5 * self.k_x_rho * self.k_x_rho

    @property
    def Gamma0(self) -> float:
        return float(gamma0(np.array([self.b]))[0])

    @property
    def analytic_residual(self) -> float:
        """Theoretical Rosenbluth-Hinton residual in the circular-tokamak limit.

            phi_res / phi_0 = 1 / (1 + 1.6 q^2 / sqrt(epsilon))
        (This is the classical result; in a slab there is no trapped-ion
        contribution so the analytic value is 1 / (1 + 0) = 1, but we
        include it here for reference.)
        """
        return 1.0 / (1.0 + 1.6 * self.q_safety ** 2 / math.sqrt(max(self.epsilon, 1.0e-6)))


# ============================================================================
# Elliptic operator for the residual
# ============================================================================
def build_residual_operator(
    mesh: RadialMesh1D,
    params: ZonalFlowParams,
) -> Tuple[np.ndarray, np.ndarray]:
    """Build the stiffness K and mass M matrices for the residual equation.

    The residual solves

        (1 + tau_e) (1 - Gamma_0) phi  -  chi_pol d^2 phi/dx^2  =  rhs

    where  chi_pol = q^2 rho_s^2 / (2 epsilon)  in the neoclassical limit
    (Hinton-Hazeltine).  In our normalised units (rho_s = 1):

        chi_pol = q^2 / (2 epsilon).

    We discretise with P1 FEM so the diffusion term contributes
    chi_pol K  and the polarisation term contributes
    (1 + tau_e) (1 - Gamma_0) M.
    """
    chi_pol = params.q_safety ** 2 / (2.0 * max(params.epsilon, 1.0e-6))
    coeff_diffusion = chi_pol
    coeff_mass = (1.0 + params.tau_e) * (1.0 - params.Gamma0)
    K, M = mesh.assemble_stiffness(kappa=1.0)
    return coeff_diffusion * K + coeff_mass * M, (K, M)


def compute_zonal_flow_residual(
    mesh: RadialMesh1D,
    phi0: np.ndarray,
    params: ZonalFlowParams,
) -> Tuple[np.ndarray, np.ndarray, float]:
    """Compute the residual zonal-flow potential.

    Given the initial potential  phi_0(x)  (typically sinusoidal),
    solve

        A phi_res  =  A0 phi_0

    where A is the operator defined above and  A0  is the same operator
    but with  chi_pol = 0  (i.e. no neoclassical polarisation --
    representing the bare initial polarisation cloud).

    Returns
    -------
    phi_res : (N,) residual potential
    rhs     : (N,) the right-hand side  A0 phi_0
    ratio   : max(|phi_res|) / max(|phi_0|)   (measured residual level)
    """
    A_full, (K, M) = build_residual_operator(mesh, params)
    # A0 = polarisation part only
    coeff_mass = (1.0 + params.tau_e) * (1.0 - params.Gamma0)
    A0 = coeff_mass * M
    rhs = A0 @ phi0
    # Dirichlet BC: phi = 0 at x = 0, Lx
    A = A_full.copy()
    A[0, :] = 0.0
    A[-1, :] = 0.0
    A[0, 0] = 1.0
    A[-1, -1] = 1.0
    rhs_bc = rhs.copy()
    rhs_bc[0] = 0.0
    rhs_bc[-1] = 0.0
    phi_res = np.linalg.solve(A, rhs_bc)
    amp_in = np.max(np.abs(phi0))
    amp_out = np.max(np.abs(phi_res))
    ratio = amp_out / amp_in if amp_in > 0 else 0.0
    return phi_res, rhs, ratio


# ============================================================================
# Time-dependent relaxation of a zonal flow (simple model)
# ============================================================================
def relax_zonal_flow(
    mesh: RadialMesh1D,
    phi0: np.ndarray,
    params: ZonalFlowParams,
    t_max: float = 50.0,
    n_steps: int = 500,
    nu_eff: float = 0.05,
) -> Tuple[np.ndarray, np.ndarray]:
    """Evolve the zonal flow under the model equation

        d phi / dt  = - nu_eff A phi

    where A is the residual operator (normalised).  This captures the
    exponential decay of the initial transient followed by saturation
    at the residual level.

    Uses implicit Euler:
        (I + dt nu_eff A) phi^{n+1} = phi^n

    Returns
    -------
    t  : (n_steps,) time array
    phi_history : (n_steps, N) field history
    """
    A, _ = build_residual_operator(mesh, params)
    # normalise by mass matrix for consistent units
    _, M = mesh.assemble_stiffness(1.0)
    M_inv_diag = 1.0 / np.maximum(np.diag(M), 1.0e-14)
    L = np.diag(M_inv_diag) @ A
    dt = t_max / n_steps
    phi = phi0.copy()
    N = phi.size
    t_arr = np.linspace(0.0, t_max, n_steps)
    phi_hist = np.zeros((n_steps, N))
    phi_hist[0] = phi
    I = np.eye(N)
    mat = I + dt * nu_eff * L
    mat[0, :] = 0.0
    mat[-1, :] = 0.0
    mat[0, 0] = 1.0
    mat[-1, -1] = 1.0
    for k in range(1, n_steps):
        rhs = phi.copy()
        rhs[0] = 0.0
        rhs[-1] = 0.0
        phi = np.linalg.solve(mat, rhs)
        phi_hist[k] = phi
    return t_arr, phi_hist


# ============================================================================
# Sanity self-check
# ============================================================================
if __name__ == "__main__":
    params = ZonalFlowParams()
    print("analytic residual (circular limit):", params.analytic_residual)
    print("Gamma0 =", params.Gamma0, " b =", params.b)
    mesh = RadialMesh1D.uniform(0.0, 1.0, 51)
    # sinusoidal initial condition
    phi0 = np.sin(math.pi * mesh.nodes)
    phi_res, rhs, ratio = compute_zonal_flow_residual(mesh, phi0, params)
    print("residual ratio:", ratio)
    t, hist = relax_zonal_flow(mesh, phi0, params, t_max=20.0, n_steps=100)
    amp = np.max(np.abs(hist), axis=1)
    print("amplitude decay: t=0:", amp[0], " t=t_max:", amp[-1])
